### ISSUE TITLE
Installed plugin but it is not visible in list of installed plugins

### ISSUE THREAD

**Issue by cygnyet** [rfinnie/OctoPrint-BedCooldown#1]
Just installed this plugin.  The install seemed successful (see log below) but no entry appears in the list of plugins.
Please advise

---------------------- log --------------------
Installing plugin "OctoPrint-BedCooldown" from https://github.com/rfinnie/OctoPrint-BedCooldown/archive/main.zip...
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install file:///tmp/tmpbtk_cktb/OctoPrint-BedCooldown-main.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /tmp/tmpbtk_cktb/OctoPrint-BedCooldown-main.zip
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-BedCooldown==0.1.0) (1.6.1)
Requirement already satisfied: cachelib<1,>=0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.2.0)
Requirement already satisfied: semantic-version<3,>=2.8.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.8.5)
Requirement already satisfied: filetype<2,>=1.0.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.0.7)
Requirement already satisfied: wrapt<2,>=1.12.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.12.1)
Requirement already satisfied: flask<2,>=1.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.1.4)
Requirement already satisfied: netaddr<1,>=0.7.19 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.8.0)
Requirement already satisfied: sarge==0.1.5post0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.1.5.post0)
Requirement already satisfied: pylru<2,>=1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.2.0)
Requirement already satisfied: sentry-sdk<1,>=0.15.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.20.3)
Requirement already satisfied: zeroconf<0.25,>=0.24 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.24.5)
Requirement already satisfied: feedparser<7,>=6.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (6.0.8)
Requirement already satisfied: itsdangerous<2,>=1.1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.1.0)
Requirement already satisfied: OctoPrint-FileCheck>=2021.2.23 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.2.23)
Requirement already satisfied: Flask-Login<0.6,>=0.5 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.5.0)
Requirement already satisfied: regex!=2018.11.6 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.4.4)
Requirement already satisfied: watchdog==0.10.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.10.4)
Requirement already satisfied: pkginfo<2,>=1.5.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.7.0)
Requirement already satisfied: unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.4.21)
Requirement already satisfied: websocket-client<1,>=0.57 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.59.0)
Requirement already satisfied: netifaces<1,>=0.10.9 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.11.0)
Requirement already satisfied: OctoPrint-PiSupport>=2021.3.26 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.8.2)
Requirement already satisfied: Flask-Babel<2,>=1.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.0.0)
Requirement already satisfied: pyserial<4,>=3.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (3.5)
Requirement already satisfied: emoji<1,>=0.5.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.6.0)
Requirement already satisfied: markupsafe<2.0,>=1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.1.1)
Requirement already satisfied: PyYAML<6,>=5.3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (5.4.1)
Requirement already satisfied: tornado==5.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (5.1.1)
Requirement already satisfied: Flask-Assets<3,>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.0)
Requirement already satisfied: psutil<6,>=5.7 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (5.8.0)
Requirement already satisfied: OctoPrint-FirmwareCheck>=2021.2.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.8.11)
Requirement already satisfied: markdown<3.2,>=3.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (3.1.1)
Requirement already satisfied: immutabledict<2,>=1.2.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.3.0)
Requirement already satisfied: requests<3,>=2.23.0 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.25.1)
Requirement already satisfied: Jinja2<3,>=2.11.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.11.3)
Requirement already satisfied: Click<8,>=7.1.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (7.1.2)
Requirement already satisfied: zipstream-new<1.2,>=1.1.8 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.1.8)
Requirement already satisfied: future<1,>=0.18.2 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.18.2)
Requirement already satisfied: blinker<2,>=1.4 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.4)
Requirement already satisfied: werkzeug<2,>=1.0.1 in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.0.1)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python3.7/site-packages (from watchdog==0.10.4->OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.1.2)
Requirement already satisfied: sgmllib3k in /home/pi/oprint/lib/python3.7/site-packages (from feedparser<7,>=6.0.2->OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.0.0)
Requirement already satisfied: webassets>=2.0 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Assets<3,>=2.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.0)
Requirement already satisfied: Babel>=2.3 in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.9.1)
Requirement already satisfied: pytz in /home/pi/oprint/lib/python3.7/site-packages (from Flask-Babel<2,>=1.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.1)
Requirement already satisfied: setuptools>=36 in /home/pi/oprint/lib/python3.7/site-packages (from markdown<3.2,>=3.1->OctoPrint->OctoPrint-BedCooldown==0.1.0) (57.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/pi/oprint/lib/python3.7/site-packages (from requests<3,>=2.23.0->OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.26.6)
Requirement already satisfied: six in /home/pi/oprint/lib/python3.7/site-packages (from websocket-client<1,>=0.57->OctoPrint->OctoPrint-BedCooldown==0.1.0) (1.16.0)
Requirement already satisfied: ifaddr in /home/pi/oprint/lib/python3.7/site-packages (from zeroconf<0.25,>=0.24->OctoPrint->OctoPrint-BedCooldown==0.1.0) (0.1.7)
Building wheels for collected packages: OctoPrint-BedCooldown
Building wheel for OctoPrint-BedCooldown (setup.py): started
Building wheel for OctoPrint-BedCooldown (setup.py): finished with status 'done'
Created wheel for OctoPrint-BedCooldown: filename=OctoPrint_BedCooldown-0.1.0-py2.py3-none-any.whl size=9051 sha256=eea63c720175b32f4934634813ddaa48367d7dd6fe1c6b70867275fe9d02aadb
Stored in directory: /tmp/pip-ephem-wheel-cache-0b26lzab/wheels/fa/db/af/b1e1b17e742b223c3ba9c61414715799ab9ae1eb18ef8bd245
Successfully built OctoPrint-BedCooldown
Installing collected packages: OctoPrint-BedCooldown
Successfully installed OctoPrint-BedCooldown-0.1.0
Done!

**Comment by KalixtShawxo** [comment]
Same issue here. 
I have installed it from the Octoprint plugin manager twice now. 
Install success, reboot, not there. Still available for install. 
Did it again, same results. Seems the installer has an issue.

**Comment by stutteringp0et** [comment]
Ditto - install success, it's listed in installed plugins - but no configuration menu item appears.

**Comment by rfinnie** [comment]
Thanks all.  FYI, restarting OctoPrint manually will get you the configuration, but I've updated the plugin with a fix which forces the restart (0.1.1).

**Comment by rfinnie** [comment]
There was also a bug with the update URL; you will need to update by installing from URL with:

https://github.com/rfinnie/OctoPrint-BedCooldown/archive/v0.1.2.zip

Sorry for the inconvenience!

**Comment by stutteringp0et** [comment]
@rfinnie 0.1.2 works for me!

**Comment by KalixtShawxo** [comment]
Worked for me too! .

Looking forward to testing it out and seeing it in Acton

**Comment by KalixtShawxo** [comment]
Doesn't seem to work on mine. I did the install of the fixed version .0.2 and it said it installed ok, and it is in the settings. I left it enabled at the default 300 seconds and 90%.
Just completed a print and watched it for the last 10%.It hit 96% before it got to 5 minutes left, and I expected the bed heating to stop when it went under 5 minutes left But nope. Bed stayed heating til the very end of the print.

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 27, 2021 at 12:51, Michael ***@***.***> wrote:   


@rfinnie 0.1.2 works for me!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KalixtShawxo** [comment]
I have now done 4 prints since then, and still none have had the print bed heater shutdown before the end of the print. Including an 8 hrs print finishing up now at 99.31% complete with 5 minutes to go. 
Is there something I need to check? 

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 28, 2021 at 0:38, Roger ***@***.***> wrote:   Doesn't seem to work on mine. I did the install of the fixed version .0.2 and it said it installed ok, and it is in the settings. I left it enabled at the default 300 seconds and 90%.
Just completed a print and watched it for the last 10%.It hit 96% before it got to 5 minutes left, and I expected the bed heating to stop when it went under 5 minutes left But nope. Bed stayed heating til the very end of the print.

Sent from Yahoo Mail on Android 
 
  On Mon, Sep 27, 2021 at 12:51, Michael ***@***.***> wrote:   


@rfinnie 0.1.2 works for me!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
