### ISSUE TITLE
version number not updated for 0.4.0 update?

### ISSUE THREAD

**Issue by th3obituary** [rfinnie/OctoPrint-BedCooldown#6]
### The problem

i thought i updated this after a print then did update it and its asking to update for a third time.
seen this happen once where the version number in the update was not changed so even though the newest version 
is installed it thinks its older and has an update loop.

hopefully im not that tired and missed anything but last time is said update was a success and on reboot i get the update info again

### Version of OctoPrint

 Connection Serial Port Baudrate Printer Profile Save connection settings Auto-connect on server startup State State: Connecting File:   Uploaded: Timelapse: On Z Change Approx. Total Print Time: - Print Time: - Print Time Left: - Printed: - Current Height: - / -mm Layer: - / - Files coasterz Size: 3.5MB Caseys Funnel.aw.gcode Uploaded: 4 hours ago Size: 3.6MB Layers: 499 Free: 4.8GB / Total: 7.0GB Create folder... Upload Upload to SD Hint: You can also drag and drop files on this page to upload them. Printer Notifications There are currently no notifications from your printer.      Dashboard     Temperature     Control     Terminal     Timelapse     Arc-Welder  [CPU Usage] 2.6% 53°C 1200MHz [RAM Usage] 39.7% [Disk Usage] 29.0% [Printer profile] SV01 [Connection status] Disconnected [Printer status] Connecting      OctoPrint 1.7.2

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

SV01 custom firmware for the btt skr mini e3 v2

### Browser and version of browser, operating system running browser

Firefox  ver. 94.02 64bit on win10 pro x64 21H2 build 19044.1387

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

did not include any of the files as i think it should be unneeded and a few i would have to look up how to find lo
[octoprint-systeminfo-20211202221257.zip](https://github.com/rfinnie/OctoPrint-BedCooldown/files/7647784/octoprint-systeminfo-20211202221257.zip)
l

**Comment by rfinnie** [comment]
Fixed as v0.4.1, thank you for reporting!
