### ISSUE TITLE
FR: Set bed temp instead of turn off bed

### ISSUE THREAD

**Issue by napter** [rfinnie/OctoPrint-BedCooldown#8]
Hey, I have a request! Near the end of the print I want to start cooling the bed but it is difficult to get the timing just right for different prints. What would help immensely is the ability to set the bed temp to a lower temp rather than turning off the bed. This way, even if the bed cools down a little early it will still retain enough adhesion.

**Comment by rfinnie** [comment]
Implemented in 0.5.0, thank you!
