### ISSUE TITLE
FR: Minimum elapsed print time 

### ISSUE THREAD

**Issue by napter** [rfinnie/OctoPrint-BedCooldown#9]
Currently the ways to avoid turning off the bed early are percent complete and time left to print. However, I believe the primary factor for whether the bed will retain heat as the print completes is how long it has been on. I haven't tested this but my theory is that when the bed  has been on for longer, various parts of the bed other than the thermistor soak up heat increasing the cooldown time. (A test would be to heat the bed and cool down as soon as it reaches temperature and heat it for say 20 minutes and see if the cooldown is slower). Presumably, this is the reason for the "percent complete" parameter, however, it isn't exactly correlated with how long the bed has been on,  

What I would like is another threshold for "minimum elapsed print time" so it will only cooldown if the print has been going on for that amount of time.

**Comment by rfinnie** [comment]
I'm not totally convinced on your theory, but FYI, the reason for the percentage trigger is to guard against really short prints. It's really just there to make sure the bed doesn't turn off immediately after the print starts and the print is trying to get adhesion on the first layer or so.

That being said, minimum elapsed was easy to implement and is in 0.5.0. Enjoy!
